// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

ResourceId constant _tableId = ResourceId.wrap(
  bytes32(abi.encodePacked(RESOURCE_TABLE, bytes14(""), bytes16("Combat")))
);
ResourceId constant CombatTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x0018060004040404040400000000000000000000000000000000000000000000
);

struct CombatData {
  int32 health;
  int32 maxHealth;
  int32 armor;
  int32 strength;
  int32 structureStrength;
  int32 counterStrength;
}

library Combat {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.BYTES32;
    _keySchema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](6);
    _valueSchema[0] = SchemaType.INT32;
    _valueSchema[1] = SchemaType.INT32;
    _valueSchema[2] = SchemaType.INT32;
    _valueSchema[3] = SchemaType.INT32;
    _valueSchema[4] = SchemaType.INT32;
    _valueSchema[5] = SchemaType.INT32;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "matchEntity";
    keyNames[1] = "entity";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](6);
    fieldNames[0] = "health";
    fieldNames[1] = "maxHealth";
    fieldNames[2] = "armor";
    fieldNames[3] = "strength";
    fieldNames[4] = "structureStrength";
    fieldNames[5] = "counterStrength";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get health.
   */
  function getHealth(bytes32 matchEntity, bytes32 entity) internal view returns (int32 health) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get health.
   */
  function _getHealth(bytes32 matchEntity, bytes32 entity) internal view returns (int32 health) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set health.
   */
  function setHealth(bytes32 matchEntity, bytes32 entity, int32 health) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((health)), _fieldLayout);
  }

  /**
   * @notice Set health.
   */
  function _setHealth(bytes32 matchEntity, bytes32 entity, int32 health) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((health)), _fieldLayout);
  }

  /**
   * @notice Get maxHealth.
   */
  function getMaxHealth(bytes32 matchEntity, bytes32 entity) internal view returns (int32 maxHealth) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get maxHealth.
   */
  function _getMaxHealth(bytes32 matchEntity, bytes32 entity) internal view returns (int32 maxHealth) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set maxHealth.
   */
  function setMaxHealth(bytes32 matchEntity, bytes32 entity, int32 maxHealth) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((maxHealth)), _fieldLayout);
  }

  /**
   * @notice Set maxHealth.
   */
  function _setMaxHealth(bytes32 matchEntity, bytes32 entity, int32 maxHealth) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((maxHealth)), _fieldLayout);
  }

  /**
   * @notice Get armor.
   */
  function getArmor(bytes32 matchEntity, bytes32 entity) internal view returns (int32 armor) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get armor.
   */
  function _getArmor(bytes32 matchEntity, bytes32 entity) internal view returns (int32 armor) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set armor.
   */
  function setArmor(bytes32 matchEntity, bytes32 entity, int32 armor) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((armor)), _fieldLayout);
  }

  /**
   * @notice Set armor.
   */
  function _setArmor(bytes32 matchEntity, bytes32 entity, int32 armor) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((armor)), _fieldLayout);
  }

  /**
   * @notice Get strength.
   */
  function getStrength(bytes32 matchEntity, bytes32 entity) internal view returns (int32 strength) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get strength.
   */
  function _getStrength(bytes32 matchEntity, bytes32 entity) internal view returns (int32 strength) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set strength.
   */
  function setStrength(bytes32 matchEntity, bytes32 entity, int32 strength) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((strength)), _fieldLayout);
  }

  /**
   * @notice Set strength.
   */
  function _setStrength(bytes32 matchEntity, bytes32 entity, int32 strength) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((strength)), _fieldLayout);
  }

  /**
   * @notice Get structureStrength.
   */
  function getStructureStrength(bytes32 matchEntity, bytes32 entity) internal view returns (int32 structureStrength) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get structureStrength.
   */
  function _getStructureStrength(bytes32 matchEntity, bytes32 entity) internal view returns (int32 structureStrength) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set structureStrength.
   */
  function setStructureStrength(bytes32 matchEntity, bytes32 entity, int32 structureStrength) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((structureStrength)), _fieldLayout);
  }

  /**
   * @notice Set structureStrength.
   */
  function _setStructureStrength(bytes32 matchEntity, bytes32 entity, int32 structureStrength) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((structureStrength)), _fieldLayout);
  }

  /**
   * @notice Get counterStrength.
   */
  function getCounterStrength(bytes32 matchEntity, bytes32 entity) internal view returns (int32 counterStrength) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get counterStrength.
   */
  function _getCounterStrength(bytes32 matchEntity, bytes32 entity) internal view returns (int32 counterStrength) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set counterStrength.
   */
  function setCounterStrength(bytes32 matchEntity, bytes32 entity, int32 counterStrength) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((counterStrength)), _fieldLayout);
  }

  /**
   * @notice Set counterStrength.
   */
  function _setCounterStrength(bytes32 matchEntity, bytes32 entity, int32 counterStrength) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((counterStrength)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 matchEntity, bytes32 entity) internal view returns (CombatData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 matchEntity, bytes32 entity) internal view returns (CombatData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 matchEntity,
    bytes32 entity,
    int32 health,
    int32 maxHealth,
    int32 armor,
    int32 strength,
    int32 structureStrength,
    int32 counterStrength
  ) internal {
    bytes memory _staticData = encodeStatic(health, maxHealth, armor, strength, structureStrength, counterStrength);

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 matchEntity,
    bytes32 entity,
    int32 health,
    int32 maxHealth,
    int32 armor,
    int32 strength,
    int32 structureStrength,
    int32 counterStrength
  ) internal {
    bytes memory _staticData = encodeStatic(health, maxHealth, armor, strength, structureStrength, counterStrength);

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 matchEntity, bytes32 entity, CombatData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.health,
      _table.maxHealth,
      _table.armor,
      _table.strength,
      _table.structureStrength,
      _table.counterStrength
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 matchEntity, bytes32 entity, CombatData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.health,
      _table.maxHealth,
      _table.armor,
      _table.strength,
      _table.structureStrength,
      _table.counterStrength
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (int32 health, int32 maxHealth, int32 armor, int32 strength, int32 structureStrength, int32 counterStrength)
  {
    health = (int32(uint32(Bytes.slice4(_blob, 0))));

    maxHealth = (int32(uint32(Bytes.slice4(_blob, 4))));

    armor = (int32(uint32(Bytes.slice4(_blob, 8))));

    strength = (int32(uint32(Bytes.slice4(_blob, 12))));

    structureStrength = (int32(uint32(Bytes.slice4(_blob, 16))));

    counterStrength = (int32(uint32(Bytes.slice4(_blob, 20))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    PackedCounter,
    bytes memory
  ) internal pure returns (CombatData memory _table) {
    (
      _table.health,
      _table.maxHealth,
      _table.armor,
      _table.strength,
      _table.structureStrength,
      _table.counterStrength
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 matchEntity, bytes32 entity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 matchEntity, bytes32 entity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    int32 health,
    int32 maxHealth,
    int32 armor,
    int32 strength,
    int32 structureStrength,
    int32 counterStrength
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(health, maxHealth, armor, strength, structureStrength, counterStrength);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dyanmic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    int32 health,
    int32 maxHealth,
    int32 armor,
    int32 strength,
    int32 structureStrength,
    int32 counterStrength
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(health, maxHealth, armor, strength, structureStrength, counterStrength);

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 matchEntity, bytes32 entity) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    return _keyTuple;
  }
}
