// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

ResourceId constant _tableId = ResourceId.wrap(
  bytes32(abi.encodePacked(RESOURCE_OFFCHAIN_TABLE, bytes14(""), bytes16("CombatResult")))
);
ResourceId constant CombatResultTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x00540a0020200404040401010101000000000000000000000000000000000000
);

struct CombatResultData {
  bytes32 attacker;
  bytes32 defender;
  int32 attackerDamageReceived;
  int32 defenderDamageReceived;
  int32 attackerDamage;
  int32 defenderDamage;
  bool ranged;
  bool attackerDied;
  bool defenderDied;
  bool defenderCaptured;
}

library CombatResult {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.BYTES32;
    _keySchema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](10);
    _valueSchema[0] = SchemaType.BYTES32;
    _valueSchema[1] = SchemaType.BYTES32;
    _valueSchema[2] = SchemaType.INT32;
    _valueSchema[3] = SchemaType.INT32;
    _valueSchema[4] = SchemaType.INT32;
    _valueSchema[5] = SchemaType.INT32;
    _valueSchema[6] = SchemaType.BOOL;
    _valueSchema[7] = SchemaType.BOOL;
    _valueSchema[8] = SchemaType.BOOL;
    _valueSchema[9] = SchemaType.BOOL;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "matchEntity";
    keyNames[1] = "entity";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](10);
    fieldNames[0] = "attacker";
    fieldNames[1] = "defender";
    fieldNames[2] = "attackerDamageReceived";
    fieldNames[3] = "defenderDamageReceived";
    fieldNames[4] = "attackerDamage";
    fieldNames[5] = "defenderDamage";
    fieldNames[6] = "ranged";
    fieldNames[7] = "attackerDied";
    fieldNames[8] = "defenderDied";
    fieldNames[9] = "defenderCaptured";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Set attacker.
   */
  function setAttacker(bytes32 matchEntity, bytes32 entity, bytes32 attacker) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((attacker)), _fieldLayout);
  }

  /**
   * @notice Set attacker.
   */
  function _setAttacker(bytes32 matchEntity, bytes32 entity, bytes32 attacker) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((attacker)), _fieldLayout);
  }

  /**
   * @notice Set defender.
   */
  function setDefender(bytes32 matchEntity, bytes32 entity, bytes32 defender) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((defender)), _fieldLayout);
  }

  /**
   * @notice Set defender.
   */
  function _setDefender(bytes32 matchEntity, bytes32 entity, bytes32 defender) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((defender)), _fieldLayout);
  }

  /**
   * @notice Set attackerDamageReceived.
   */
  function setAttackerDamageReceived(bytes32 matchEntity, bytes32 entity, int32 attackerDamageReceived) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((attackerDamageReceived)), _fieldLayout);
  }

  /**
   * @notice Set attackerDamageReceived.
   */
  function _setAttackerDamageReceived(bytes32 matchEntity, bytes32 entity, int32 attackerDamageReceived) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((attackerDamageReceived)), _fieldLayout);
  }

  /**
   * @notice Set defenderDamageReceived.
   */
  function setDefenderDamageReceived(bytes32 matchEntity, bytes32 entity, int32 defenderDamageReceived) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((defenderDamageReceived)), _fieldLayout);
  }

  /**
   * @notice Set defenderDamageReceived.
   */
  function _setDefenderDamageReceived(bytes32 matchEntity, bytes32 entity, int32 defenderDamageReceived) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((defenderDamageReceived)), _fieldLayout);
  }

  /**
   * @notice Set attackerDamage.
   */
  function setAttackerDamage(bytes32 matchEntity, bytes32 entity, int32 attackerDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((attackerDamage)), _fieldLayout);
  }

  /**
   * @notice Set attackerDamage.
   */
  function _setAttackerDamage(bytes32 matchEntity, bytes32 entity, int32 attackerDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((attackerDamage)), _fieldLayout);
  }

  /**
   * @notice Set defenderDamage.
   */
  function setDefenderDamage(bytes32 matchEntity, bytes32 entity, int32 defenderDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((defenderDamage)), _fieldLayout);
  }

  /**
   * @notice Set defenderDamage.
   */
  function _setDefenderDamage(bytes32 matchEntity, bytes32 entity, int32 defenderDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((defenderDamage)), _fieldLayout);
  }

  /**
   * @notice Set ranged.
   */
  function setRanged(bytes32 matchEntity, bytes32 entity, bool ranged) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((ranged)), _fieldLayout);
  }

  /**
   * @notice Set ranged.
   */
  function _setRanged(bytes32 matchEntity, bytes32 entity, bool ranged) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((ranged)), _fieldLayout);
  }

  /**
   * @notice Set attackerDied.
   */
  function setAttackerDied(bytes32 matchEntity, bytes32 entity, bool attackerDied) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((attackerDied)), _fieldLayout);
  }

  /**
   * @notice Set attackerDied.
   */
  function _setAttackerDied(bytes32 matchEntity, bytes32 entity, bool attackerDied) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((attackerDied)), _fieldLayout);
  }

  /**
   * @notice Set defenderDied.
   */
  function setDefenderDied(bytes32 matchEntity, bytes32 entity, bool defenderDied) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((defenderDied)), _fieldLayout);
  }

  /**
   * @notice Set defenderDied.
   */
  function _setDefenderDied(bytes32 matchEntity, bytes32 entity, bool defenderDied) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((defenderDied)), _fieldLayout);
  }

  /**
   * @notice Set defenderCaptured.
   */
  function setDefenderCaptured(bytes32 matchEntity, bytes32 entity, bool defenderCaptured) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((defenderCaptured)), _fieldLayout);
  }

  /**
   * @notice Set defenderCaptured.
   */
  function _setDefenderCaptured(bytes32 matchEntity, bytes32 entity, bool defenderCaptured) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((defenderCaptured)), _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 matchEntity,
    bytes32 entity,
    bytes32 attacker,
    bytes32 defender,
    int32 attackerDamageReceived,
    int32 defenderDamageReceived,
    int32 attackerDamage,
    int32 defenderDamage,
    bool ranged,
    bool attackerDied,
    bool defenderDied,
    bool defenderCaptured
  ) internal {
    bytes memory _staticData = encodeStatic(
      attacker,
      defender,
      attackerDamageReceived,
      defenderDamageReceived,
      attackerDamage,
      defenderDamage,
      ranged,
      attackerDied,
      defenderDied,
      defenderCaptured
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 matchEntity,
    bytes32 entity,
    bytes32 attacker,
    bytes32 defender,
    int32 attackerDamageReceived,
    int32 defenderDamageReceived,
    int32 attackerDamage,
    int32 defenderDamage,
    bool ranged,
    bool attackerDied,
    bool defenderDied,
    bool defenderCaptured
  ) internal {
    bytes memory _staticData = encodeStatic(
      attacker,
      defender,
      attackerDamageReceived,
      defenderDamageReceived,
      attackerDamage,
      defenderDamage,
      ranged,
      attackerDied,
      defenderDied,
      defenderCaptured
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 matchEntity, bytes32 entity, CombatResultData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.attacker,
      _table.defender,
      _table.attackerDamageReceived,
      _table.defenderDamageReceived,
      _table.attackerDamage,
      _table.defenderDamage,
      _table.ranged,
      _table.attackerDied,
      _table.defenderDied,
      _table.defenderCaptured
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 matchEntity, bytes32 entity, CombatResultData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.attacker,
      _table.defender,
      _table.attackerDamageReceived,
      _table.defenderDamageReceived,
      _table.attackerDamage,
      _table.defenderDamage,
      _table.ranged,
      _table.attackerDied,
      _table.defenderDied,
      _table.defenderCaptured
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      bytes32 attacker,
      bytes32 defender,
      int32 attackerDamageReceived,
      int32 defenderDamageReceived,
      int32 attackerDamage,
      int32 defenderDamage,
      bool ranged,
      bool attackerDied,
      bool defenderDied,
      bool defenderCaptured
    )
  {
    attacker = (Bytes.slice32(_blob, 0));

    defender = (Bytes.slice32(_blob, 32));

    attackerDamageReceived = (int32(uint32(Bytes.slice4(_blob, 64))));

    defenderDamageReceived = (int32(uint32(Bytes.slice4(_blob, 68))));

    attackerDamage = (int32(uint32(Bytes.slice4(_blob, 72))));

    defenderDamage = (int32(uint32(Bytes.slice4(_blob, 76))));

    ranged = (_toBool(uint8(Bytes.slice1(_blob, 80))));

    attackerDied = (_toBool(uint8(Bytes.slice1(_blob, 81))));

    defenderDied = (_toBool(uint8(Bytes.slice1(_blob, 82))));

    defenderCaptured = (_toBool(uint8(Bytes.slice1(_blob, 83))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    PackedCounter,
    bytes memory
  ) internal pure returns (CombatResultData memory _table) {
    (
      _table.attacker,
      _table.defender,
      _table.attackerDamageReceived,
      _table.defenderDamageReceived,
      _table.attackerDamage,
      _table.defenderDamage,
      _table.ranged,
      _table.attackerDied,
      _table.defenderDied,
      _table.defenderCaptured
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 matchEntity, bytes32 entity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 matchEntity, bytes32 entity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    bytes32 attacker,
    bytes32 defender,
    int32 attackerDamageReceived,
    int32 defenderDamageReceived,
    int32 attackerDamage,
    int32 defenderDamage,
    bool ranged,
    bool attackerDied,
    bool defenderDied,
    bool defenderCaptured
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        attacker,
        defender,
        attackerDamageReceived,
        defenderDamageReceived,
        attackerDamage,
        defenderDamage,
        ranged,
        attackerDied,
        defenderDied,
        defenderCaptured
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dyanmic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bytes32 attacker,
    bytes32 defender,
    int32 attackerDamageReceived,
    int32 defenderDamageReceived,
    int32 attackerDamage,
    int32 defenderDamage,
    bool ranged,
    bool attackerDied,
    bool defenderDied,
    bool defenderCaptured
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(
      attacker,
      defender,
      attackerDamageReceived,
      defenderDamageReceived,
      attackerDamage,
      defenderDamage,
      ranged,
      attackerDied,
      defenderDied,
      defenderCaptured
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 matchEntity, bytes32 entity) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = matchEntity;
    _keyTuple[1] = entity;

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
