// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct SeasonPassSaleData {
  uint256 price;
  uint256 purchasedAt;
  address tokenAddress;
}

library SeasonPassSale {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "SeasonPassSale", typeId: RESOURCE_OFFCHAIN_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x6f740000000000000000000000000000536561736f6e5061737353616c650000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0054030020201400000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (address, uint256)
  Schema constant _keySchema = Schema.wrap(0x00340200611f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, address)
  Schema constant _valueSchema = Schema.wrap(0x005403001f1f6100000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "buyer";
    keyNames[1] = "tokenId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "price";
    fieldNames[1] = "purchasedAt";
    fieldNames[2] = "tokenAddress";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Set price.
   */
  function setPrice(address buyer, uint256 tokenId, uint256 price) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((price)), _fieldLayout);
  }

  /**
   * @notice Set price.
   */
  function _setPrice(address buyer, uint256 tokenId, uint256 price) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((price)), _fieldLayout);
  }

  /**
   * @notice Set purchasedAt.
   */
  function setPurchasedAt(address buyer, uint256 tokenId, uint256 purchasedAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((purchasedAt)), _fieldLayout);
  }

  /**
   * @notice Set purchasedAt.
   */
  function _setPurchasedAt(address buyer, uint256 tokenId, uint256 purchasedAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((purchasedAt)), _fieldLayout);
  }

  /**
   * @notice Set tokenAddress.
   */
  function setTokenAddress(address buyer, uint256 tokenId, address tokenAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((tokenAddress)), _fieldLayout);
  }

  /**
   * @notice Set tokenAddress.
   */
  function _setTokenAddress(address buyer, uint256 tokenId, address tokenAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((tokenAddress)), _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(address buyer, uint256 tokenId, uint256 price, uint256 purchasedAt, address tokenAddress) internal {
    bytes memory _staticData = encodeStatic(price, purchasedAt, tokenAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(address buyer, uint256 tokenId, uint256 price, uint256 purchasedAt, address tokenAddress) internal {
    bytes memory _staticData = encodeStatic(price, purchasedAt, tokenAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(address buyer, uint256 tokenId, SeasonPassSaleData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.price, _table.purchasedAt, _table.tokenAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(address buyer, uint256 tokenId, SeasonPassSaleData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.price, _table.purchasedAt, _table.tokenAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 price, uint256 purchasedAt, address tokenAddress) {
    price = (uint256(Bytes.getBytes32(_blob, 0)));

    purchasedAt = (uint256(Bytes.getBytes32(_blob, 32)));

    tokenAddress = (address(Bytes.getBytes20(_blob, 64)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (SeasonPassSaleData memory _table) {
    (_table.price, _table.purchasedAt, _table.tokenAddress) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(address buyer, uint256 tokenId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(address buyer, uint256 tokenId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 price, uint256 purchasedAt, address tokenAddress) internal pure returns (bytes memory) {
    return abi.encodePacked(price, purchasedAt, tokenAddress);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 price,
    uint256 purchasedAt,
    address tokenAddress
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(price, purchasedAt, tokenAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(address buyer, uint256 tokenId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(buyer)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    return _keyTuple;
  }
}
