export const TIPS = [
  "Press [F] to toggle fullscreen.",
  "You don't need to own a Summoning Altar to use it. Simply move two of the same type of unit next to it to merge them.",
  "Press [ENTER] to cycle through your units with available energy points.",
  "Higher tiered units are not only stronger, but have higher max energy points and energy regen rate!",
  "Infantry type units (Swordsman, Pikeman, etc) are good in frontline combat: they can deal a lot of damage when attacking and defending.",
  "Cavalry type units (Pillager, Knight, etc) have low strength and deal less damage when defending, but are fast.",
  "Ranged type units (Archer, Catapult, etc) have low strength and deal less damage when defending, but can attack from a distance. Note: They cannot attack units directly next to them.",
  "All structures that produce units (Settlements, Villages) can run out of energy points. When this happens, they will never produce units again.",
  "The live launch of Sky Strife will run a rollup based on Optimism Bedrock with data availability on Ethereum Mainnet.",
  "Whoever manages to capture the Ember Crown and escape through an Escape Portal will win the game!",
  "The Ember Crown spawns in the center of the map inside of the Ember Crown Shrine. Once activated, the Crown can be retrieved after 5 Energy Surges.",
  "Left click to select a unit. Right click to move.",
  "After selecting a unit, right clicking is context sensitive. If you right click on a unit, it will attack. If you right click something that generates a resource, it will harvest it.",
  "There are three types of military units: Infantry, Cavalry, and Ranged. Each type has a different role in combat.",
  "There are three tiers of units. Each tier is stronger than the previous one. In order to get higher tier units, you need to merge lower tier units at a Summoning Altar.",
  "Everything in Sky Strife uses Energy Points to act. Energy Points regenerate during an Energy Surge, which happens every 60 seconds.",
  "Different types of Terrain have different movement costs. For example, Forests have a movement cost of 1.5 tiles, while Mountains have a movement cost of 2.",
  "Different types of Terrain give strength bonuses to units during combat. For example, engaging in combat on a Forest tile gives +3 strength",
  "The difference in strength between two units is used to determine damage in battle. The unit with the higher strength will deal more damage.",
  "Amplifiers are special items that can be held by your units to increase their stats. There are three types of Amplifiers: Strength, Movement, and Energy.",
  "Amplifiers can be obtained in two ways: crafting them in your Amalgema wallet using resources found in a match, or stolen from other players!",
];
