// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EncodedLengths } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { createTemplate } from "base/libraries/templates/createTemplate.sol";
import { UnitTypes, CombatArchetypes, TerrainTypes, StructureTypes } from "base/codegen/common.sol";

import { Combat, StructureType, Untraversable, GoldOnKill } from "base/codegen/index.sol";

bytes32 constant templateId = "GoldCache";
bytes32 constant GoldCacheTemplateId = templateId;
uint256 constant LENGTH = 4;

function GoldCacheTemplate() {
  bytes32[] memory tableIds = new bytes32[](LENGTH);
  bytes32[] memory encodedLengthss = new bytes32[](LENGTH);
  bytes[] memory staticDatas = new bytes[](LENGTH);
  bytes[] memory dynamicDatas = new bytes[](LENGTH);

  bytes memory staticData;
  EncodedLengths encodedLengths;
  bytes memory dynamicData;

  tableIds[0] = ResourceId.unwrap(Combat._tableId);
  tableIds[1] = ResourceId.unwrap(StructureType._tableId);
  tableIds[2] = ResourceId.unwrap(Untraversable._tableId);
  tableIds[3] = ResourceId.unwrap(GoldOnKill._tableId);

  (staticData, encodedLengths, dynamicData) = Combat.encode(100000, 100000, 0, 0, 0, 0, CombatArchetypes(uint8(11)));
  staticDatas[0] = staticData;
  encodedLengthss[0] = EncodedLengths.unwrap(encodedLengths);
  dynamicDatas[0] = dynamicData;

  (staticData, encodedLengths, dynamicData) = StructureType.encode(StructureTypes(uint8(5)));
  staticDatas[1] = staticData;
  encodedLengthss[1] = EncodedLengths.unwrap(encodedLengths);
  dynamicDatas[1] = dynamicData;

  (staticData, encodedLengths, dynamicData) = Untraversable.encode(true);
  staticDatas[2] = staticData;
  encodedLengthss[2] = EncodedLengths.unwrap(encodedLengths);
  dynamicDatas[2] = dynamicData;

  (staticData, encodedLengths, dynamicData) = GoldOnKill.encode(250);
  staticDatas[3] = staticData;
  encodedLengthss[3] = EncodedLengths.unwrap(encodedLengths);
  dynamicDatas[3] = dynamicData;

  createTemplate(templateId, tableIds, staticDatas, encodedLengthss, dynamicDatas);
}
