// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum UnitTypes {
  Unknown,
  Swordsman,
  Pikeman,
  Halberdier,
  Pillager,
  Knight,
  Dragoon,
  Archer,
  Catapult,
  Marksman,
  Brute
}

enum CombatArchetypes {
  Unknown,
  Swordsman,
  Pikeman,
  Halberdier,
  Pillager,
  Knight,
  Dragoon,
  Archer,
  Catapult,
  Marksman,
  Settlement,
  SpawnSettlement,
  GoldMine,
  Brute
}

enum TerrainTypes {
  Unknown,
  Grass,
  Mountain,
  Forest
}

enum StructureTypes {
  Unknown,
  Settlement,
  SpawnSettlement,
  WoodenWall,
  GoldMine,
  GoldCache
}
