// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum UnitTypes {
  Unknown,
  Swordsman,
  Pikeman,
  Golem,
  Rider,
  Knight,
  Dragon,
  Archer,
  Catapult,
  Wizard
}

enum TerrainTypes {
  Unknown,
  Grass,
  Mountain,
  Water,
  Wall,
  Forest,
  StoneWall,
  LavaGround,
  LavaMountain,
  LavaForest,
  Lava,
  RockWall
}

enum StructureTypes {
  Unknown,
  Settlement,
  SpawnSettlement,
  GoldShrine,
  EscapePortal,
  Portal,
  Container,
  SummoningAltar,
  BlazingHeartShrine,
  WoodenWall,
  GoldMine,
  Village,
  EmberCrownShrine,
  CrystalGenerator,
  MetalGenerator,
  FossilGenerator,
  WidgetGenerator
}

enum ItemTypes {
  Unknown,
  Gold,
  EmberCrown,
  BlazingHeart,
  MovementBanner,
  SwordBanner,
  StaminaBanner,
  Crystal,
  Metal,
  Fossil,
  Widget
}
