// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { SwordsmanTemplate, SwordsmanTemplateId } from "./templates/SwordsmanTemplate.sol";
import { PikemanTemplate, PikemanTemplateId } from "./templates/PikemanTemplate.sol";
import { HalberdierTemplate, HalberdierTemplateId } from "./templates/HalberdierTemplate.sol";
import { GodUnitTemplate, GodUnitTemplateId } from "./templates/GodUnitTemplate.sol";
import { PillagerTemplate, PillagerTemplateId } from "./templates/PillagerTemplate.sol";
import { KnightTemplate, KnightTemplateId } from "./templates/KnightTemplate.sol";
import { DragoonTemplate, DragoonTemplateId } from "./templates/DragoonTemplate.sol";
import { ArcherTemplate, ArcherTemplateId } from "./templates/ArcherTemplate.sol";
import { CatapultTemplate, CatapultTemplateId } from "./templates/CatapultTemplate.sol";
import { MarksmanTemplate, MarksmanTemplateId } from "./templates/MarksmanTemplate.sol";
import { BruteTemplate, BruteTemplateId } from "./templates/BruteTemplate.sol";
import { GrassTemplate, GrassTemplateId } from "./templates/GrassTemplate.sol";
import { MountainTemplate, MountainTemplateId } from "./templates/MountainTemplate.sol";
import { WaterTemplate, WaterTemplateId } from "./templates/WaterTemplate.sol";
import { ForestTemplate, ForestTemplateId } from "./templates/ForestTemplate.sol";
import { StoneWallTemplate, StoneWallTemplateId } from "./templates/StoneWallTemplate.sol";
import { LavaGroundTemplate, LavaGroundTemplateId } from "./templates/LavaGroundTemplate.sol";
import { LavaTemplate, LavaTemplateId } from "./templates/LavaTemplate.sol";
import { LavaMountainTemplate, LavaMountainTemplateId } from "./templates/LavaMountainTemplate.sol";
import { LavaForestTemplate, LavaForestTemplateId } from "./templates/LavaForestTemplate.sol";
import { RockWallTemplate, RockWallTemplateId } from "./templates/RockWallTemplate.sol";
import { MapCenterMarkerTemplate, MapCenterMarkerTemplateId } from "./templates/MapCenterMarkerTemplate.sol";
import { SettlementTemplate, SettlementTemplateId } from "./templates/SettlementTemplate.sol";
import { SpawnSettlementTemplate, SpawnSettlementTemplateId } from "./templates/SpawnSettlementTemplate.sol";
import { GoldMineTemplate, GoldMineTemplateId } from "./templates/GoldMineTemplate.sol";
import { WoodenWallTemplate, WoodenWallTemplateId } from "./templates/WoodenWallTemplate.sol";
