// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "./../index.sol";

/**
 * @title IBuildSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBuildSystem {
  function build(
    bytes32 matchEntity,
    bytes32 factoryEntity,
    bytes32 templateId,
    PositionData memory coord
  ) external returns (bytes32);
}
