// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IHeroConfigSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IHeroConfigSystem {
  function setHeroInRotation(bytes32 template, bool inRotation) external;

  function setHeroInSeasonPassRotation(bytes32 template, bool inRotation) external;
}
