// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title INameSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface INameSystem {
  function setName(string memory name) external;
}
