// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISeasonPassSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISeasonPassSystem {
  function buySeasonPass(address account) external payable;
}
