// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "./../tables/Position.sol";

/**
 * @title ITemplateSpawnSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITemplateSpawnSystem {
  function spawnTemplate(
    bytes32 matchEntity,
    bytes32 prototypeId,
    bytes32 ownerId,
    PositionData memory position
  ) external;
}
