// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { SwordsmanTemplate, PikemanTemplate, HalberdierTemplate, GodUnitTemplate, PillagerTemplate, KnightTemplate, DragoonTemplate, ArcherTemplate, CatapultTemplate, MarksmanTemplate, BruteTemplate, GrassTemplate, MountainTemplate, WaterTemplate, ForestTemplate, StoneWallTemplate, LavaGroundTemplate, LavaTemplate, LavaMountainTemplate, LavaForestTemplate, RockWallTemplate, MapCenterMarkerTemplate, SettlementTemplate, SpawnSettlementTemplate, GoldMineTemplate, WoodenWallTemplate } from "../Templates.sol";

function createTemplates() {
  SwordsmanTemplate();
  PikemanTemplate();
  HalberdierTemplate();
  GodUnitTemplate();
  PillagerTemplate();
  KnightTemplate();
  DragoonTemplate();
  ArcherTemplate();
  CatapultTemplate();
  MarksmanTemplate();
  BruteTemplate();
  GrassTemplate();
  MountainTemplate();
  WaterTemplate();
  ForestTemplate();
  StoneWallTemplate();
  LavaGroundTemplate();
  LavaTemplate();
  LavaMountainTemplate();
  LavaForestTemplate();
  RockWallTemplate();
  MapCenterMarkerTemplate();
  SettlementTemplate();
  SpawnSettlementTemplate();
  GoldMineTemplate();
  WoodenWallTemplate();
}
