// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SwordsmanTemplate, PikemanTemplate, HalberdierTemplate, GodUnitTemplate, PillagerTemplate, KnightTemplate, DragoonTemplate, ArcherTemplate, CatapultTemplate, MarksmanTemplate, BruteTemplate, GrassTemplate, MountainTemplate, ForestTemplate, MapCenterMarkerTemplate, SettlementTemplate, SpawnSettlementTemplate, GoldMineTemplate, GoldCacheTemplate, WoodenWallTemplate } from "../Templates.sol";

function createTemplates() {
  SwordsmanTemplate();
  PikemanTemplate();
  HalberdierTemplate();
  GodUnitTemplate();
  PillagerTemplate();
  KnightTemplate();
  DragoonTemplate();
  ArcherTemplate();
  CatapultTemplate();
  MarksmanTemplate();
  BruteTemplate();
  GrassTemplate();
  MountainTemplate();
  ForestTemplate();
  MapCenterMarkerTemplate();
  SettlementTemplate();
  SpawnSettlementTemplate();
  GoldMineTemplate();
  GoldCacheTemplate();
  WoodenWallTemplate();
}
